### ISSUE TITLE
3D animated model ?

### ISSUE THREAD

**Issue by RUSshy** [ClintKilmer/CKGL#1]
Hi,
I'm looking for a simple engine in C# that support 3d animated model, do you plan to add this ?
Ty!

**Comment by ClintKilmer** [comment]
Hey RUSshy. This is definitely on my list, but not in the immediate future. Currently I'm implementing 3 Graphics Backends: Vulkan, OpenGL, and OpenGL ES.

My goal for this project is to expose a simple drawing library like Gamemaker Studio 2, and have the graphics backends take care of everything.

Feel free to use anything you find in my project. Other projects you could look through on github would be FNA, MonoGame, Veldrid, or Rise.
